version: '3.9'
services:
  http-backend:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.http
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET} 
  ws-backend:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.fe
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_WEBSOCKET_URL: ${NEXT_PUBLIC_WEBSOCKET_URL}
    ports:
      - "3000:3000"
