version: '3.9'
services:
  postgres:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exclidraw
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  http-backend:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.http
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
  ws-backend:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.fe
    ports:
      - "3000:3000"
volumes:
  postgres-data:
