FROM node:20-alpine
ARG DATABASE_URL

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN pnpm install
RUN pnpm --filter web run build
EXPOSE 3000

CMD [ "pnpm","run","start"]
