name: deploy image
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.HOST_IP}}
          username: ${{secrets.HOST_NAME}}
          key: ${{secrets.AWS_KEY}}
          port: 22
          script: ./deploy.sh